name: Automatic GitHub Pages generation

on:
  page_build:
  release:
    types:
      - created
  workflow_dispatch:
jobs:
  update-docs-on-gh-pages-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.1
        env:
          # The branch where the files will be copied from
          key: 'master'
          # The destination branch
          branches: 'gh-pages'
          # The files that will be copied
          files: 'README.md'
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
    - uses: itamarc/action-itemplate-ghpages@v1test
      with:
        templates_folder: ':dark:'
        pages_branch: 'gh-pages'
        pages_folder: 'docs'
        timezone: 'America/Sao_Paulo'
        publish_readme_md: 'inline'
        syntax_highlight_enable: 'true'
        syntax_highlight_theme: 'tomorrow'
        log_level: 'INFO'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
